//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Tier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VTP-PC\\VOTUANPHUONG;Initial Catalog=Northwind;Integrated Security=Tru" +
            "e;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string NorthwindConnectionString {
            get {
                return ((string)(this["NorthwindConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VTP-PC\\VOTUANPHUONG;Initial Catalog=qlQT;Integrated Security=True;Con" +
            "nect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string qlQTConnectionString {
            get {
                return ((string)(this["qlQTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Initial Catalog=qlQT;Integrated Security=True;Enc" +
            "rypt=False;TrustServerCertificate=True")]
        public string qlQTConnectionString1 {
            get {
                return ((string)(this["qlQTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Integrated Security=True;Encrypt=False;TrustServe" +
            "rCertificate=True")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Initial Catalog=qlQT_c;Integrated Security=True;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string qlQT_cConnectionString {
            get {
                return ((string)(this["qlQT_cConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Initial Catalog=qlQT_a;Integrated Security=True;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string qlQT_aConnectionString {
            get {
                return ((string)(this["qlQT_aConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Initial Catalog=qlQT_b;Integrated Security=True;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string qlQT_bConnectionString {
            get {
                return ((string)(this["qlQT_bConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=H92M03\\MSSQLSERVER1;Initial Catalog=qlQT_d;Integrated Security=True;E" +
            "ncrypt=False;TrustServerCertificate=True")]
        public string qlQT_dConnectionString {
            get {
                return ((string)(this["qlQT_dConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VTP-PC\\VOTUANPHUONG;Initial Catalog=QL_QUAYTHUOC;Integrated Security=" +
            "True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string QL_QUAYTHUOCConnectionString {
            get {
                return ((string)(this["QL_QUAYTHUOCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VTP-PC\\VOTUANPHUONG;Initial Catalog=DrugStoreDB;Integrated Security=T" +
            "rue;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string DrugStoreDBConnectionString {
            get {
                return ((string)(this["DrugStoreDBConnectionString"]));
            }
        }
    }
}
