#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Tier
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DrugStoreDB")]
	public partial class DrugStoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertthuoc(thuoc instance);
    partial void Updatethuoc(thuoc instance);
    partial void Deletethuoc(thuoc instance);
    partial void Insertnuoc(nuoc instance);
    partial void Updatenuoc(nuoc instance);
    partial void Deletenuoc(nuoc instance);
    partial void InsertnhanVien(nhanVien instance);
    partial void UpdatenhanVien(nhanVien instance);
    partial void DeletenhanVien(nhanVien instance);
    partial void InsertnhaCungCap(nhaCungCap instance);
    partial void UpdatenhaCungCap(nhaCungCap instance);
    partial void DeletenhaCungCap(nhaCungCap instance);
    partial void InsertloaiThuoc(loaiThuoc instance);
    partial void UpdateloaiThuoc(loaiThuoc instance);
    partial void DeleteloaiThuoc(loaiThuoc instance);
    partial void InsertloaiNhanVien(loaiNhanVien instance);
    partial void UpdateloaiNhanVien(loaiNhanVien instance);
    partial void DeleteloaiNhanVien(loaiNhanVien instance);
    partial void InsertkhachHang(khachHang instance);
    partial void UpdatekhachHang(khachHang instance);
    partial void DeletekhachHang(khachHang instance);
    partial void InserthoaDon(hoaDon instance);
    partial void UpdatehoaDon(hoaDon instance);
    partial void DeletehoaDon(hoaDon instance);
    partial void InsertdonViTinh(donViTinh instance);
    partial void UpdatedonViTinh(donViTinh instance);
    partial void DeletedonViTinh(donViTinh instance);
    partial void Insertct_hoaDon(ct_hoaDon instance);
    partial void Updatect_hoaDon(ct_hoaDon instance);
    partial void Deletect_hoaDon(ct_hoaDon instance);
    #endregion
		
		public DrugStoreDataContext() : 
				base(global::Data_Tier.Properties.Settings.Default.DrugStoreDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DrugStoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugStoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugStoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DrugStoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<thuoc> thuocs
		{
			get
			{
				return this.GetTable<thuoc>();
			}
		}
		
		public System.Data.Linq.Table<taiKhoan> taiKhoans
		{
			get
			{
				return this.GetTable<taiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<nuoc> nuocs
		{
			get
			{
				return this.GetTable<nuoc>();
			}
		}
		
		public System.Data.Linq.Table<nhanVien> nhanViens
		{
			get
			{
				return this.GetTable<nhanVien>();
			}
		}
		
		public System.Data.Linq.Table<nhaCungCap> nhaCungCaps
		{
			get
			{
				return this.GetTable<nhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<loaiThuoc> loaiThuocs
		{
			get
			{
				return this.GetTable<loaiThuoc>();
			}
		}
		
		public System.Data.Linq.Table<loaiNhanVien> loaiNhanViens
		{
			get
			{
				return this.GetTable<loaiNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<khachHang> khachHangs
		{
			get
			{
				return this.GetTable<khachHang>();
			}
		}
		
		public System.Data.Linq.Table<hoaDon> hoaDons
		{
			get
			{
				return this.GetTable<hoaDon>();
			}
		}
		
		public System.Data.Linq.Table<donViTinh> donViTinhs
		{
			get
			{
				return this.GetTable<donViTinh>();
			}
		}
		
		public System.Data.Linq.Table<ct_hoaDon> ct_hoaDons
		{
			get
			{
				return this.GetTable<ct_hoaDon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thuoc")]
	public partial class thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maThuoc;
		
		private string _tenThuoc;
		
		private System.Nullable<int> _maNCC;
		
		private string _moTa;
		
		private string _maLoai;
		
		private string _maDVT;
		
		private System.Nullable<decimal> _giaGoc;
		
		private System.Nullable<decimal> _giaBan;
		
		private System.Nullable<int> _slTon;
		
		private string _maNuoc;
		
		private System.Nullable<System.DateTime> _hanSuDung;
		
		private EntitySet<ct_hoaDon> _ct_hoaDons;
		
		private EntityRef<nuoc> _nuoc;
		
		private EntityRef<nhaCungCap> _nhaCungCap;
		
		private EntityRef<loaiThuoc> _loaiThuoc;
		
		private EntityRef<donViTinh> _donViTinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OntenThuocChanging(string value);
    partial void OntenThuocChanged();
    partial void OnmaNCCChanging(System.Nullable<int> value);
    partial void OnmaNCCChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OnmaDVTChanging(string value);
    partial void OnmaDVTChanged();
    partial void OngiaGocChanging(System.Nullable<decimal> value);
    partial void OngiaGocChanged();
    partial void OngiaBanChanging(System.Nullable<decimal> value);
    partial void OngiaBanChanged();
    partial void OnslTonChanging(System.Nullable<int> value);
    partial void OnslTonChanged();
    partial void OnmaNuocChanging(string value);
    partial void OnmaNuocChanged();
    partial void OnhanSuDungChanging(System.Nullable<System.DateTime> value);
    partial void OnhanSuDungChanged();
    #endregion
		
		public thuoc()
		{
			this._ct_hoaDons = new EntitySet<ct_hoaDon>(new Action<ct_hoaDon>(this.attach_ct_hoaDons), new Action<ct_hoaDon>(this.detach_ct_hoaDons));
			this._nuoc = default(EntityRef<nuoc>);
			this._nhaCungCap = default(EntityRef<nhaCungCap>);
			this._loaiThuoc = default(EntityRef<loaiThuoc>);
			this._donViTinh = default(EntityRef<donViTinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="NChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenThuoc", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string tenThuoc
		{
			get
			{
				return this._tenThuoc;
			}
			set
			{
				if ((this._tenThuoc != value))
				{
					this.OntenThuocChanging(value);
					this.SendPropertyChanging();
					this._tenThuoc = value;
					this.SendPropertyChanged("tenThuoc");
					this.OntenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="Int")]
		public System.Nullable<int> maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					if (this._nhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(700)")]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NChar(3)")]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._loaiThuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDVT", DbType="NChar(3)")]
		public string maDVT
		{
			get
			{
				return this._maDVT;
			}
			set
			{
				if ((this._maDVT != value))
				{
					if (this._donViTinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDVTChanging(value);
					this.SendPropertyChanging();
					this._maDVT = value;
					this.SendPropertyChanged("maDVT");
					this.OnmaDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaGoc", DbType="Money")]
		public System.Nullable<decimal> giaGoc
		{
			get
			{
				return this._giaGoc;
			}
			set
			{
				if ((this._giaGoc != value))
				{
					this.OngiaGocChanging(value);
					this.SendPropertyChanging();
					this._giaGoc = value;
					this.SendPropertyChanged("giaGoc");
					this.OngiaGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Money")]
		public System.Nullable<decimal> giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slTon", DbType="Int")]
		public System.Nullable<int> slTon
		{
			get
			{
				return this._slTon;
			}
			set
			{
				if ((this._slTon != value))
				{
					this.OnslTonChanging(value);
					this.SendPropertyChanging();
					this._slTon = value;
					this.SendPropertyChanged("slTon");
					this.OnslTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNuoc", DbType="NChar(3)")]
		public string maNuoc
		{
			get
			{
				return this._maNuoc;
			}
			set
			{
				if ((this._maNuoc != value))
				{
					if (this._nuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNuocChanging(value);
					this.SendPropertyChanging();
					this._maNuoc = value;
					this.SendPropertyChanged("maNuoc");
					this.OnmaNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanSuDung", DbType="DateTime")]
		public System.Nullable<System.DateTime> hanSuDung
		{
			get
			{
				return this._hanSuDung;
			}
			set
			{
				if ((this._hanSuDung != value))
				{
					this.OnhanSuDungChanging(value);
					this.SendPropertyChanging();
					this._hanSuDung = value;
					this.SendPropertyChanged("hanSuDung");
					this.OnhanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thuoc_ct_hoaDon", Storage="_ct_hoaDons", ThisKey="maThuoc", OtherKey="maThuoc")]
		public EntitySet<ct_hoaDon> ct_hoaDons
		{
			get
			{
				return this._ct_hoaDons;
			}
			set
			{
				this._ct_hoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nuoc_thuoc", Storage="_nuoc", ThisKey="maNuoc", OtherKey="maNuoc", IsForeignKey=true)]
		public nuoc nuoc
		{
			get
			{
				return this._nuoc.Entity;
			}
			set
			{
				nuoc previousValue = this._nuoc.Entity;
				if (((previousValue != value) 
							|| (this._nuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nuoc.Entity = null;
						previousValue.thuocs.Remove(this);
					}
					this._nuoc.Entity = value;
					if ((value != null))
					{
						value.thuocs.Add(this);
						this._maNuoc = value.maNuoc;
					}
					else
					{
						this._maNuoc = default(string);
					}
					this.SendPropertyChanged("nuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaCungCap_thuoc", Storage="_nhaCungCap", ThisKey="maNCC", OtherKey="maNCC", IsForeignKey=true)]
		public nhaCungCap nhaCungCap
		{
			get
			{
				return this._nhaCungCap.Entity;
			}
			set
			{
				nhaCungCap previousValue = this._nhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._nhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhaCungCap.Entity = null;
						previousValue.thuocs.Remove(this);
					}
					this._nhaCungCap.Entity = value;
					if ((value != null))
					{
						value.thuocs.Add(this);
						this._maNCC = value.maNCC;
					}
					else
					{
						this._maNCC = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiThuoc_thuoc", Storage="_loaiThuoc", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public loaiThuoc loaiThuoc
		{
			get
			{
				return this._loaiThuoc.Entity;
			}
			set
			{
				loaiThuoc previousValue = this._loaiThuoc.Entity;
				if (((previousValue != value) 
							|| (this._loaiThuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiThuoc.Entity = null;
						previousValue.thuocs.Remove(this);
					}
					this._loaiThuoc.Entity = value;
					if ((value != null))
					{
						value.thuocs.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("loaiThuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donViTinh_thuoc", Storage="_donViTinh", ThisKey="maDVT", OtherKey="maDVT", IsForeignKey=true)]
		public donViTinh donViTinh
		{
			get
			{
				return this._donViTinh.Entity;
			}
			set
			{
				donViTinh previousValue = this._donViTinh.Entity;
				if (((previousValue != value) 
							|| (this._donViTinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._donViTinh.Entity = null;
						previousValue.thuocs.Remove(this);
					}
					this._donViTinh.Entity = value;
					if ((value != null))
					{
						value.thuocs.Add(this);
						this._maDVT = value.maDVT;
					}
					else
					{
						this._maDVT = default(string);
					}
					this.SendPropertyChanged("donViTinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ct_hoaDons(ct_hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.thuoc = this;
		}
		
		private void detach_ct_hoaDons(ct_hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.taiKhoan")]
	public partial class taiKhoan
	{
		
		private string _matKhau;
		
		private string _maNV;
		
		public taiKhoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this._matKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NChar(5) NOT NULL", CanBeNull=false)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this._maNV = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nuoc")]
	public partial class nuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNuoc;
		
		private string _tenNuoc;
		
		private EntitySet<thuoc> _thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNuocChanging(string value);
    partial void OnmaNuocChanged();
    partial void OntenNuocChanging(string value);
    partial void OntenNuocChanged();
    #endregion
		
		public nuoc()
		{
			this._thuocs = new EntitySet<thuoc>(new Action<thuoc>(this.attach_thuocs), new Action<thuoc>(this.detach_thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNuoc", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNuoc
		{
			get
			{
				return this._maNuoc;
			}
			set
			{
				if ((this._maNuoc != value))
				{
					this.OnmaNuocChanging(value);
					this.SendPropertyChanging();
					this._maNuoc = value;
					this.SendPropertyChanged("maNuoc");
					this.OnmaNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNuoc", DbType="NVarChar(30)")]
		public string tenNuoc
		{
			get
			{
				return this._tenNuoc;
			}
			set
			{
				if ((this._tenNuoc != value))
				{
					this.OntenNuocChanging(value);
					this.SendPropertyChanging();
					this._tenNuoc = value;
					this.SendPropertyChanged("tenNuoc");
					this.OntenNuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nuoc_thuoc", Storage="_thuocs", ThisKey="maNuoc", OtherKey="maNuoc")]
		public EntitySet<thuoc> thuocs
		{
			get
			{
				return this._thuocs;
			}
			set
			{
				this._thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.nuoc = this;
		}
		
		private void detach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.nuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanVien")]
	public partial class nhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _tenNV;
		
		private string _diaChi;
		
		private string _dienThoai;
		
		private string _maLoaiNV;
		
		private EntitySet<hoaDon> _hoaDons;
		
		private EntityRef<loaiNhanVien> _loaiNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndienThoaiChanging(string value);
    partial void OndienThoaiChanged();
    partial void OnmaLoaiNVChanging(string value);
    partial void OnmaLoaiNVChanged();
    #endregion
		
		public nhanVien()
		{
			this._hoaDons = new EntitySet<hoaDon>(new Action<hoaDon>(this.attach_hoaDons), new Action<hoaDon>(this.detach_hoaDons));
			this._loaiNhanVien = default(EntityRef<loaiNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(500)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dienThoai", DbType="NVarChar(24)")]
		public string dienThoai
		{
			get
			{
				return this._dienThoai;
			}
			set
			{
				if ((this._dienThoai != value))
				{
					this.OndienThoaiChanging(value);
					this.SendPropertyChanging();
					this._dienThoai = value;
					this.SendPropertyChanged("dienThoai");
					this.OndienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiNV", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string maLoaiNV
		{
			get
			{
				return this._maLoaiNV;
			}
			set
			{
				if ((this._maLoaiNV != value))
				{
					if (this._loaiNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._maLoaiNV = value;
					this.SendPropertyChanged("maLoaiNV");
					this.OnmaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoaDon", Storage="_hoaDons", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<hoaDon> hoaDons
		{
			get
			{
				return this._hoaDons;
			}
			set
			{
				this._hoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiNhanVien_nhanVien", Storage="_loaiNhanVien", ThisKey="maLoaiNV", OtherKey="maLoaiNV", IsForeignKey=true)]
		public loaiNhanVien loaiNhanVien
		{
			get
			{
				return this._loaiNhanVien.Entity;
			}
			set
			{
				loaiNhanVien previousValue = this._loaiNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._loaiNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiNhanVien.Entity = null;
						previousValue.nhanViens.Remove(this);
					}
					this._loaiNhanVien.Entity = value;
					if ((value != null))
					{
						value.nhanViens.Add(this);
						this._maLoaiNV = value.maLoaiNV;
					}
					else
					{
						this._maLoaiNV = default(string);
					}
					this.SendPropertyChanged("loaiNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoaDons(hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_hoaDons(hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhaCungCap")]
	public partial class nhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maNCC;
		
		private string _tenNCC;
		
		private string _diaChi;
		
		private string _phone;
		
		private EntitySet<thuoc> _thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNCCChanging(int value);
    partial void OnmaNCCChanged();
    partial void OntenNCCChanging(string value);
    partial void OntenNCCChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public nhaCungCap()
		{
			this._thuocs = new EntitySet<thuoc>(new Action<thuoc>(this.attach_thuocs), new Action<thuoc>(this.detach_thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNCC", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maNCC
		{
			get
			{
				return this._maNCC;
			}
			set
			{
				if ((this._maNCC != value))
				{
					this.OnmaNCCChanging(value);
					this.SendPropertyChanging();
					this._maNCC = value;
					this.SendPropertyChanged("maNCC");
					this.OnmaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNCC", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string tenNCC
		{
			get
			{
				return this._tenNCC;
			}
			set
			{
				if ((this._tenNCC != value))
				{
					this.OntenNCCChanging(value);
					this.SendPropertyChanging();
					this._tenNCC = value;
					this.SendPropertyChanged("tenNCC");
					this.OntenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(500)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(15)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhaCungCap_thuoc", Storage="_thuocs", ThisKey="maNCC", OtherKey="maNCC")]
		public EntitySet<thuoc> thuocs
		{
			get
			{
				return this._thuocs;
			}
			set
			{
				this._thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.nhaCungCap = this;
		}
		
		private void detach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.nhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiThuoc")]
	public partial class loaiThuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<thuoc> _thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public loaiThuoc()
		{
			this._thuocs = new EntitySet<thuoc>(new Action<thuoc>(this.attach_thuocs), new Action<thuoc>(this.detach_thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(30)")]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiThuoc_thuoc", Storage="_thuocs", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<thuoc> thuocs
		{
			get
			{
				return this._thuocs;
			}
			set
			{
				this._thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.loaiThuoc = this;
		}
		
		private void detach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.loaiThuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiNhanVien")]
	public partial class loaiNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoaiNV;
		
		private string _tenLoaiNV;
		
		private EntitySet<nhanVien> _nhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiNVChanging(string value);
    partial void OnmaLoaiNVChanged();
    partial void OntenLoaiNVChanging(string value);
    partial void OntenLoaiNVChanged();
    #endregion
		
		public loaiNhanVien()
		{
			this._nhanViens = new EntitySet<nhanVien>(new Action<nhanVien>(this.attach_nhanViens), new Action<nhanVien>(this.detach_nhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiNV", DbType="NChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoaiNV
		{
			get
			{
				return this._maLoaiNV;
			}
			set
			{
				if ((this._maLoaiNV != value))
				{
					this.OnmaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._maLoaiNV = value;
					this.SendPropertyChanged("maLoaiNV");
					this.OnmaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiNV", DbType="NVarChar(50)")]
		public string tenLoaiNV
		{
			get
			{
				return this._tenLoaiNV;
			}
			set
			{
				if ((this._tenLoaiNV != value))
				{
					this.OntenLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiNV = value;
					this.SendPropertyChanged("tenLoaiNV");
					this.OntenLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiNhanVien_nhanVien", Storage="_nhanViens", ThisKey="maLoaiNV", OtherKey="maLoaiNV")]
		public EntitySet<nhanVien> nhanViens
		{
			get
			{
				return this._nhanViens;
			}
			set
			{
				this._nhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.loaiNhanVien = this;
		}
		
		private void detach_nhanViens(nhanVien entity)
		{
			this.SendPropertyChanging();
			entity.loaiNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachHang")]
	public partial class khachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _tenKH;
		
		private string _diaChi;
		
		private string _phone;
		
		private EntitySet<hoaDon> _hoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public khachHang()
		{
			this._hoaDons = new EntitySet<hoaDon>(new Action<hoaDon>(this.attach_hoaDons), new Action<hoaDon>(this.detach_hoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(500)")]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(24)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoaDon", Storage="_hoaDons", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<hoaDon> hoaDons
		{
			get
			{
				return this._hoaDons;
			}
			set
			{
				this._hoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoaDons(hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = this;
		}
		
		private void detach_hoaDons(hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoaDon")]
	public partial class hoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHoaDon;
		
		private System.Nullable<System.DateTime> _ngayLapHD;
		
		private string _maNV;
		
		private string _maKH;
		
		private EntitySet<ct_hoaDon> _ct_hoaDons;
		
		private EntityRef<khachHang> _khachHang;
		
		private EntityRef<nhanVien> _nhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(int value);
    partial void OnmaHoaDonChanged();
    partial void OnngayLapHDChanging(System.Nullable<System.DateTime> value);
    partial void OnngayLapHDChanged();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    #endregion
		
		public hoaDon()
		{
			this._ct_hoaDons = new EntitySet<ct_hoaDon>(new Action<ct_hoaDon>(this.attach_ct_hoaDons), new Action<ct_hoaDon>(this.detach_ct_hoaDons));
			this._khachHang = default(EntityRef<khachHang>);
			this._nhanVien = default(EntityRef<nhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLapHD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayLapHD
		{
			get
			{
				return this._ngayLapHD;
			}
			set
			{
				if ((this._ngayLapHD != value))
				{
					this.OnngayLapHDChanging(value);
					this.SendPropertyChanging();
					this._ngayLapHD = value;
					this.SendPropertyChanged("ngayLapHD");
					this.OnngayLapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="NChar(5)")]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="NChar(5)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._khachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaDon_ct_hoaDon", Storage="_ct_hoaDons", ThisKey="maHoaDon", OtherKey="maHD")]
		public EntitySet<ct_hoaDon> ct_hoaDons
		{
			get
			{
				return this._ct_hoaDons;
			}
			set
			{
				this._ct_hoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_hoaDon", Storage="_khachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public khachHang khachHang
		{
			get
			{
				return this._khachHang.Entity;
			}
			set
			{
				khachHang previousValue = this._khachHang.Entity;
				if (((previousValue != value) 
							|| (this._khachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachHang.Entity = null;
						previousValue.hoaDons.Remove(this);
					}
					this._khachHang.Entity = value;
					if ((value != null))
					{
						value.hoaDons.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("khachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_hoaDon", Storage="_nhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.hoaDons.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.hoaDons.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ct_hoaDons(ct_hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hoaDon = this;
		}
		
		private void detach_ct_hoaDons(ct_hoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.donViTinh")]
	public partial class donViTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDVT;
		
		private string _tenDVT;
		
		private EntitySet<thuoc> _thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDVTChanging(string value);
    partial void OnmaDVTChanged();
    partial void OntenDVTChanging(string value);
    partial void OntenDVTChanged();
    #endregion
		
		public donViTinh()
		{
			this._thuocs = new EntitySet<thuoc>(new Action<thuoc>(this.attach_thuocs), new Action<thuoc>(this.detach_thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDVT", DbType="NChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDVT
		{
			get
			{
				return this._maDVT;
			}
			set
			{
				if ((this._maDVT != value))
				{
					this.OnmaDVTChanging(value);
					this.SendPropertyChanging();
					this._maDVT = value;
					this.SendPropertyChanged("maDVT");
					this.OnmaDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenDVT", DbType="NVarChar(20)")]
		public string tenDVT
		{
			get
			{
				return this._tenDVT;
			}
			set
			{
				if ((this._tenDVT != value))
				{
					this.OntenDVTChanging(value);
					this.SendPropertyChanging();
					this._tenDVT = value;
					this.SendPropertyChanged("tenDVT");
					this.OntenDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donViTinh_thuoc", Storage="_thuocs", ThisKey="maDVT", OtherKey="maDVT")]
		public EntitySet<thuoc> thuocs
		{
			get
			{
				return this._thuocs;
			}
			set
			{
				this._thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.donViTinh = this;
		}
		
		private void detach_thuocs(thuoc entity)
		{
			this.SendPropertyChanging();
			entity.donViTinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ct_hoaDon")]
	public partial class ct_hoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maHD;
		
		private string _maThuoc;
		
		private System.Nullable<int> _soLuong;
		
		private System.Nullable<decimal> _donGia;
		
		private System.Nullable<double> _thue;
		
		private EntityRef<hoaDon> _hoaDon;
		
		private EntityRef<thuoc> _thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(int value);
    partial void OnmaHDChanged();
    partial void OnmaThuocChanging(string value);
    partial void OnmaThuocChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OndonGiaChanging(System.Nullable<decimal> value);
    partial void OndonGiaChanged();
    partial void OnthueChanging(System.Nullable<double> value);
    partial void OnthueChanged();
    #endregion
		
		public ct_hoaDon()
		{
			this._hoaDon = default(EntityRef<hoaDon>);
			this._thuoc = default(EntityRef<thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._hoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maThuoc", DbType="NChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maThuoc
		{
			get
			{
				return this._maThuoc;
			}
			set
			{
				if ((this._maThuoc != value))
				{
					if (this._thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaThuocChanging(value);
					this.SendPropertyChanging();
					this._maThuoc = value;
					this.SendPropertyChanged("maThuoc");
					this.OnmaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Money")]
		public System.Nullable<decimal> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thue", DbType="Float")]
		public System.Nullable<double> thue
		{
			get
			{
				return this._thue;
			}
			set
			{
				if ((this._thue != value))
				{
					this.OnthueChanging(value);
					this.SendPropertyChanging();
					this._thue = value;
					this.SendPropertyChanged("thue");
					this.OnthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaDon_ct_hoaDon", Storage="_hoaDon", ThisKey="maHD", OtherKey="maHoaDon", IsForeignKey=true)]
		public hoaDon hoaDon
		{
			get
			{
				return this._hoaDon.Entity;
			}
			set
			{
				hoaDon previousValue = this._hoaDon.Entity;
				if (((previousValue != value) 
							|| (this._hoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoaDon.Entity = null;
						previousValue.ct_hoaDons.Remove(this);
					}
					this._hoaDon.Entity = value;
					if ((value != null))
					{
						value.ct_hoaDons.Add(this);
						this._maHD = value.maHoaDon;
					}
					else
					{
						this._maHD = default(int);
					}
					this.SendPropertyChanged("hoaDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="thuoc_ct_hoaDon", Storage="_thuoc", ThisKey="maThuoc", OtherKey="maThuoc", IsForeignKey=true)]
		public thuoc thuoc
		{
			get
			{
				return this._thuoc.Entity;
			}
			set
			{
				thuoc previousValue = this._thuoc.Entity;
				if (((previousValue != value) 
							|| (this._thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._thuoc.Entity = null;
						previousValue.ct_hoaDons.Remove(this);
					}
					this._thuoc.Entity = value;
					if ((value != null))
					{
						value.ct_hoaDons.Add(this);
						this._maThuoc = value.maThuoc;
					}
					else
					{
						this._maThuoc = default(string);
					}
					this.SendPropertyChanged("thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
